### ISSUE TITLE
can't open webpage

### ISSUE THREAD

**Issue by Yannik25** [makermoekoe/Octoclick#1]
as the title says, I can't open the webpage to view the detailed description of the Octoclick.

**Comment by labomat** [comment]
The website https://makermoekoe.com/2020/04/28/a-dashbutton-for-the-internet-of-things-called-octoclick/ is accessible by me.

**Comment by Yannik25** [comment]
Yes he has rewritten the Website

**Comment by labomat** [comment]
But can you access the files link? See my other issue?

**Comment by Yannik25** [comment]
No, and he was also not responding via email last time
